# Generated by Django 4.1.5 on 2023-01-26 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0003_alter_address_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="address",
        ),
        migrations.AddField(
            model_name="address",
            name="person",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="person.person",
            ),
            preserve_default=False,
        ),
    ]
